"""Chronological Random Forest regime classification and evaluation.

Labels are generated by the existing rule detector. This model therefore
learns to approximate that transparent baseline; it is not a claim that the
rule labels are objective market truth.
"""
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score, recall_score

from indicators import compute_indicators
from regime import detect_regimes

RANDOM_STATE = 42
REGIMES = ["Bull Trend", "Bear Trend", "Range / Sideways", "High Volatility"]
FEATURES = ["rsi_14", "macd_hist", "roc_10", "adx_14", "hist_vol_20", "vol_percentile", "bb_width_pct", "volume_vs_avg_pct", "close_vs_sma20_pct", "close_vs_sma50_pct"]
MIN_SAMPLES = 40


def _dataset(df: pd.DataFrame, interval: str = "1d"):
    if df is None or len(df) < MIN_SAMPLES:
        raise ValueError(f"At least {MIN_SAMPLES} bars are required for chronological ML evaluation.")
    ind = compute_indicators(df, interval)
    ind["close_vs_sma20_pct"] = (ind["Close"] / ind["sma_20"] - 1) * 100
    ind["close_vs_sma50_pct"] = (ind["Close"] / ind["sma_50"] - 1) * 100
    labels = detect_regimes(df, interval=interval)["regime"].rename("target")
    data = ind[FEATURES].join(labels).replace([np.inf, -np.inf], np.nan).dropna()
    if len(data) < MIN_SAMPLES:
        raise ValueError("Insufficient valid indicator history after warm-up; request a longer period.")
    present = [r for r in REGIMES if r in set(data.target)]
    if len(present) < 2:
        raise ValueError("At least two rule-based regimes must be present to train the classifier.")
    return data, present


def _make_model(max_depth=None):
    return RandomForestClassifier(n_estimators=300, max_depth=max_depth, min_samples_leaf=2,
                                  class_weight="balanced_subsample", random_state=RANDOM_STATE,
                                  n_jobs=-1)


def evaluate_regime_model(df: pd.DataFrame, interval: str = "1d") -> dict:
    """Chronological 60/20/20 split. Validation selects depth; test is untouched."""
    data, labels = _dataset(df, interval)
    n = len(data)
    train_end, val_end = int(n * .60), int(n * .80)
    if train_end < 20 or val_end - train_end < 5 or n - val_end < 5:
        raise ValueError("Not enough valid rows for chronological train/validation/test splits.")
    X, y = data[FEATURES], data.target
    candidates = [4, 8, None]
    scored = []
    for depth in candidates:
        if y.iloc[:train_end].nunique() < 2:
            raise ValueError("Training window contains fewer than two regimes; use a longer or more varied history.")
        model = _make_model(depth).fit(X.iloc[:train_end], y.iloc[:train_end])
        pred = model.predict(X.iloc[train_end:val_end])
        scored.append((f1_score(y.iloc[train_end:val_end], pred, labels=labels, average="macro", zero_division=0), depth))
    best_depth = max(scored, key=lambda item: item[0])[1]
    model = _make_model(best_depth).fit(X.iloc[:val_end], y.iloc[:val_end])
    y_test, p_test = y.iloc[val_end:], model.predict(X.iloc[val_end:])
    report = classification_report(y_test, p_test, labels=labels, output_dict=True, zero_division=0)
    cm = confusion_matrix(y_test, p_test, labels=labels).tolist()
    return {
        "split": {"method": "chronological", "train_pct": 60, "validation_pct": 20, "test_pct": 20,
                  "train_rows": train_end, "validation_rows": val_end - train_end, "test_rows": n - val_end,
                  "first_date": str(data.index[0]), "train_end": str(data.index[train_end - 1]),
                  "validation_end": str(data.index[val_end - 1]), "test_start": str(data.index[val_end]),
                  "test_end": str(data.index[-1])},
        "target_definition": "Existing rule-based regime labels; ML learns to approximate the rules.",
        "metrics": {"accuracy": round(float(accuracy_score(y_test, p_test)), 4),
                    "precision_macro": round(float(precision_score(y_test, p_test, labels=labels, average="macro", zero_division=0)), 4),
                    "recall_macro": round(float(recall_score(y_test, p_test, labels=labels, average="macro", zero_division=0)), 4),
                    "f1_macro": round(float(f1_score(y_test, p_test, labels=labels, average="macro", zero_division=0)), 4),
                    "per_class": {label: {metric: round(float(report[label][metric]), 4) for metric in ("precision", "recall", "f1-score", "support")} for label in labels},
                    "confusion_matrix": {"labels": labels, "matrix": cm}},
        "validation_macro_f1": round(max(scored, key=lambda item: item[0])[0], 4),
        "selected_max_depth": best_depth,
        "features": FEATURES,
        "feature_importance": [{"feature": feature, "importance": round(float(value), 6)} for feature, value in sorted(zip(FEATURES, model.feature_importances_), key=lambda item: item[1], reverse=True)],
    }


def predict_regime(df: pd.DataFrame, interval: str = "1d") -> dict:
    """Predict the latest bar from a forest trained only on earlier bars."""
    data, _ = _dataset(df, interval)
    if len(data) < 2:
        raise ValueError("At least two valid feature rows are required for prediction.")
    X, y = data[FEATURES], data.target
    if y.iloc[:-1].nunique() < 2:
        raise ValueError("History before the latest bar contains fewer than two regimes; request a longer period.")
    model = _make_model(8).fit(X.iloc[:-1], y.iloc[:-1])
    row = X.iloc[[-1]]
    pred = model.predict(row)[0]
    probs = model.predict_proba(row)[0]
    probability_by_class = dict(zip(model.classes_, probs))
    probabilities = {label: round(float(probability_by_class.get(label, 0.0)), 4) for label in REGIMES}
    important = sorted(zip(FEATURES, model.feature_importances_), key=lambda item: item[1], reverse=True)[:5]
    rule = str(data.target.iloc[-1])
    return {"predicted_regime": str(pred), "confidence": round(float(max(probs)), 4),
            "class_probabilities": probabilities,
            "important_features": [{"feature": feature, "importance": round(float(value), 6)} for feature, value in important],
            "rule_based_regime": rule, "agreement": bool(pred == rule),
            "comparison": "Agreement" if pred == rule else "Disagreement",
            "as_of": str(data.index[-1]), "trained_through": str(data.index[-2]),
            "target_definition": "Prediction of the existing rule-based labels, not an independent market-truth label."}

